# Generated by Django 4.2 on 2024-12-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beasiswaalumni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengelolaandana',
            old_name='tanggal_pencarian',
            new_name='tanggal_pencairan',
        ),
        migrations.RemoveField(
            model_name='donasi',
            name='status_dacc',
        ),
        migrations.AlterField(
            model_name='akun',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='login',
            name='jenis_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='jenis_program',
            field=models.CharField(choices=[('affirmasi', 'Affirmasi'), ('prestasi', 'Prestasi')], max_length=100),
        ),
    ]
