# Generated by Django 4.2 on 2024-12-14 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beasiswaalumni', '0002_rename_tanggal_pencarian_pengelolaandana_tanggal_pencairan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='status_lolos',
            field=models.CharField(choices=[('Lolos', 'Lolos'), ('Tidak', 'Tidak')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pengelolaandana',
            name='status_pencairan',
            field=models.CharField(choices=[('BELUM CAIR', 'Belum Cair'), ('SUDAH CAIR', 'Sudah Cair'), ('DALAM PROSES', 'Dalam Proses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='persyaratankhusus',
            name='persyaratan',
            field=models.FileField(blank=True, null=True, upload_to='persyaratan_khusus/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='jenis_program',
            field=models.CharField(choices=[('afirmasi', 'Afirmasi'), ('prestasi', 'Prestasi')], max_length=100),
        ),
        migrations.CreateModel(
            name='Pengumpulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beasiswaalumni.pendaftaran')),
                ('id_persyaratanKhusus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beasiswaalumni.persyaratankhusus')),
            ],
        ),
    ]
